shop/urls.py
from django.conf.urls import url
from . import views

app_name = 'shop'
urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^all/(?P<page>\d*[1-9]\d*/)?$', views.view_all, name='all'),
    url(r'^search/(?P<page>\d*[1-9]\d*/)?$', views.search, name='search'),
    url(r'^product/(?P<id>\d*[1-9]\d*)/$', views.view_product,
        name='viewproduct'),
    url(r'^product/(?P<id>\d*[1-9]\d*)/reviews/(?P<reviewid>\d*[1-9]\d*)'
        r'/delete/$', views.review_delete, name='deletereview'),
    url(r'^product/(?P<id>\d*[1-9]\d*)/reviews/$', views.view_reviews,
        name='reviews'),
    url(r'^product/(?P<id>\d*[1-9]\d*)/addtocart/$', views.add_to_cart,
        name='addtocart'),
    url(r'^product/(?P<id>\d*[1-9]\d*)/edit/$', views.edit_product,
        name='editproduct'),
    url(r'^product/(?P<id>\d*[1-9]\d*)/edit/files/$', views.edit_keys,
        name='editkeys'),
    url(r'^product/(?P<id>\d*[1-9]\d*)/edit/files/key/'
        r'(?P<keyid>\d*[1-9]\d*)?/?$', views.manage_keyset, name='managekey'),
    url(r'^product/(?P<id>\d*[1-9]\d*)/edit/keys/upload/$',
        views.upload_file_noapi, name='uploadfilenoapi'),
    url(r'^shop/(?P<user>[A-Za-z0-9\-\_]{1,150})/$', views.shop, name='shop'),
    url(r'^me/cart/$', views.view_cart, name='cart'),
    url(r'^me/cart/remove/(?P<id>\d*[1-9]\d*)/$', views.remove_cart,
        name='removecart'),
    url(r'^me/cart/checkout/$', views.checkout, name='checkout'),
    url(r'^me/shop/edit/$', views.editshop, name='editshop'),
    url(r'^me/wallets/$', views.wallets, name='wallets'),
    url(r'^me/settings/$', views.my_settings, name='settings'),
    url(r'^me/settings/account/changepassword/$', views.change_password,
        name='changepassword'),
    url(r'^me/settings/2fa/$', views.auth_settings, name='2fasettings'),
    url(r'^me/settings/2fa/google/$', views.google_settings,
        name='googlesettings'),
    url(r'^me/purchases/$', views.purchases, name='purchases'),
    url(r'^me/purchases/keys/$', views.keys, name='keys'),
    url(r'^me/purchases/keys/download/(?P<id>\d*[1-9]\d*)/$',
        views.download_file, name='download'),
    url(r'^me/purchases/orders/$', views.orders, name='orders'),
    url(r'^me/purchases/orders/(?P<id>\d*[1-9]\d*)/$', views.view_order,
        name='vieworder'),
    url(r'^me/purchases/(?P<uuid>[A-Za-z0-9\-\_]{36})/$', views.view_purchase,
        name='purchase'),
    url(r'^me/dashboard/$', views.dashboard, name='dashboard'),
    url(r'^me/dashboard/sales/$', views.seller_purchases, name='sales'),
    url(r'^me/dashboard/sales/(?P<id>\d*[1-9]\d*)/$', views.manage_order,
        name='manageorder'),
    url(r'^me/dashboard/new/$', views.sell_new_product, name='sellproduct'),
    url(r'^accounts/login/$', views.login_view, name='login'),
    url(r'^accounts/register/$', views.register_view, name='register'),
    url(r'^accounts/logout/$', views.logoutview, name='logout'),
    url(r'^accounts/authorize/(?P<forid>[A-Za-z0-9\-\_]{1,32})/$',
        views.authorize, name='authorize'),
    url(r'^accounts/verify/(?P<uuid>[^/]+)/$', views.verify_email,
        name='verifyemail'),
    url(r'^api/wallets/newwallet/$', views.api_newwallet, name='apinewwallet'),
    url(r'^api/wallets/checkaddress/$', views.api_checkaddress,
        name='apicheckaddress'),
    url(r'^api/wallets/send/$', views.api_send, name='apisend'),
    url(r'^api/keys/get/$', views.get_key, name='getkey'),
    url(r'^api/qrcode/$', views.qr_code, name='qrcode'),
    url(r'^api/uploadpic/$', views.upload_pic, name='uploadpic'),
    url(r'^api/deletepic/(?P<uuid>[A-Za-z0-9\-\_]{36})/$', views.delete_pic,
        name='deletepic'),
    url(r'^api/uploadfile/(?P<id>\d*[1-9]\d*)/$', views.upload_file,
        name='uploadfile'),
    url(r'^api/deletefile/(?P<id>\d*[1-9]\d*)/$', views.delete_file,
        name='deletefile'),
    url(r'^api/vote/(?P<id>\d*[1-9]\d*)/(?P<vote>up|down)', views.toggle_vote,
        name='togglevote'),
]

shop/models.py
import uuid
import os

from django.db import models
from django.db.models import F
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.mail import send_mail
from django_countries.fields import CountryField
from django.conf import settings
from . import cryptomethods as cm
from decimal import Decimal
from bitcoinrpc.authproxy import JSONRPCException
import cryptonator
import pyotp


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('upload', filename)


def get_protected_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('protected', filename)


def send_confirmation_email(user):
    if user.email != '':
        v = VerifyEmail(user=user)
        v.save()
        body = """
Hello, %s! To complete your registration on OKShop, please verify your email by
clicking the following link:
https://%s%s""" % (user.username, getattr(settings, 'URL', 'okcart.net'),
                   reverse('shop:verifyemail', kwargs={'uuid': v.verify_url}))
        send_mail('Complete your OKShop registration!', body,
                  'no-reply@okcart.net', [user.email])


class Product(models.Model):
    # If you can't fit your product's name into a tweet you need a better name
    product_name = models.CharField(max_length=140)
    product_description = models.TextField()
    approved = models.BooleanField(default=True)

    price = models.DecimalField(max_digits=1000, decimal_places=8)
    price_currency = models.CharField(max_length=16, default='OK')
    cached_rate = models.DecimalField(blank=True, null=True, max_digits=1000,
                                      decimal_places=8)
    rate_lastupdated = models.DateTimeField(default=timezone.now)

    physical = models.BooleanField(default=0)
    stock = models.IntegerField(blank=True, null=True)

    date = models.DateTimeField(default=timezone.now)

    seller = models.ForeignKey(User)

    free_shipping = models.BooleanField(default=False)
    worldwide_shipping = models.BooleanField(default=False)
    ships_from = CountryField(null=True, blank=True)
    local_price = models.DecimalField(max_digits=1000, decimal_places=8,
                                      default=0)
    outside_price = models.DecimalField(max_digits=1000, decimal_places=8,
                                        default=0)

    redeeming_instructions = models.TextField(default='', blank=True,
                                              null=True)
    unlimited_stock = models.BooleanField(default=False)

    can_purchase_multiple = models.BooleanField(default=True)
    delete_on_over = models.BooleanField(default=False)
    removed = models.BooleanField(default=False)

    def __str__(self):
        return self.product_name

    def in_stock(self):
        if self.stock == 0 and not self.unlimited_stock:
            return False
        else:
            return True

    def get_absolute_url(self):
        return reverse('shop:viewproduct', kwargs={'id': self.id})

    def ships_to(self, a):
        if self.worldwide_shipping or not self.physical:
            return True
        if self.shippingcountry_set.filter(country=a.country[0]).count() >= 1:
            return True
        return False

    def get_shipping_price(self, address=None):
        if self.free_shipping or not self.physical:
            return 0
        if self.ships_from == address.country:
            if self.price_currency != 'OK':
                if not self.cached_rate or \
                 timezone.now() - self.rate_lastupdated \
                 >= timezone.timedelta(hours=1):
                    self.rate_lastupdated = timezone.now()
                    self.cached_rate = Decimal(cryptonator.get_exchange_rate(
                        self.price_currency, 'ok'))
                    self.save()
                return Decimal(self.cached_rate) * Decimal(self.local_price)
            return self.local_price
        if self.price_currency != 'OK':
            if not self.cached_rate or \
             timezone.now() - self.rate_lastupdated \
             >= timezone.timedelta(hours=1):
                self.rate_lastupdated = timezone.now()
                self.cached_rate = Decimal(cryptonator.get_exchange_rate(
                    self.price_currency, 'ok'))
                self.save()
            return Decimal(self.cached_rate) * Decimal(self.outside_price)
        return self.outside_price

    def buy(self, address, wallet, ammount, gift=False):
        if not hasattr(self.seller, 'usershop'):
            if self.seller.wallet_set.filter(active=True).count() > 0:
                a = self.seller.wallet_set.filter(active=True).first()
            else:
                a = Wallet(user=self.seller, label='Store payments')
                a.save()
            us = UserShop(user=self.seller, pay_to_address=a)
            us.save()
        if (self.stock >= ammount or self.unlimited_stock) and \
                self.ships_to(address) and not self.removed:
            if getattr(settings, 'FEE_ADDRESS', '') != '':
                wallet.send_to(
                    getattr(settings, 'FEE_ADDRESS', ''),
                    (self.get_shipping_price(address)
                     + self.get_item_price()*ammount) * Decimal(0.005))
                wallet.send_to(
                    self.seller.usershop.pay_to_address.address,
                    (self.get_shipping_price(address)
                     + self.get_item_price()*ammount) * Decimal(0.995))
                fee = 0.995
            else:
                wallet.send_to(
                    self.seller.usershop.pay_to_address.address,
                    (self.get_shipping_price(address)
                     + self.get_item_price() * Decimal(ammount)))
                fee = 1
            if not self.unlimited_stock:
                self.stock -= ammount
                if self.delete_on_over and self.stock == 0:
                    self.removed = True
            self.save()
            send_mail("Someone bought one of your items!", """Hello %s,

The user %s has purchased your product, %s.
We recommend you get in contact with the buyer as fast as possible.

Thanks for selling with OKCart!""" % (self.seller.username,
                                      wallet.user.username, self.product_name),
                      "no_reply@okcart.net", [self.seller.email])
            return PurchaseItem(
                product=self, gift=gift,
                price=self.get_item_price(),
                quantity=ammount,
                shipping_price=self.get_shipping_price(address),
                address=address,
                fee=fee
            )

    def get_earnings(self):
        s = 0
        for p in PurchaseItem.objects.filter(product=self):
            s += p.price
        return s

    def get_purchases(self):
        return PurchaseItem.objects.filter(product=self)

    def get_item_price(self):
        if self.price_currency != 'OK':
            if not self.cached_rate or \
             timezone.now() - self.rate_lastupdated \
             >= timezone.timedelta(hours=1):
                self.rate_lastupdated = timezone.now()
                self.cached_rate = Decimal(cryptonator.get_exchange_rate(
                    self.price_currency, 'ok'))
                self.save()
            return Decimal(self.cached_rate) * Decimal(self.price)
        return self.price

    def update_rates(self):
        self.cached_rate = cryptonator.get_exchange_rate(self.price_currency,
                                                         'ok')
        self.save()

    def ships_to_country(self, country):
        return self.shippingcountry_set.filter(country=country[0]).count() > 0

    def get_rating(self):
        s = []
        for review in self.review_set.all():
            s.append(review.rating)
        if len(s):
            return sum(s) / len(s)
        return 0

    get_rating.short_description = 'rating'

    def is_owned_by(self, user):
        return self.purchaseitem_set.filter(purchase__by=user).count() > 0


class ShippingCountry(models.Model):
    product = models.ForeignKey(Product)
    country = CountryField()

    class Meta:
        verbose_name_plural = "shipping countries"

    def __str__(self):
        return '%s ships to %s!' % (self.product, self.country)


class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True)
    image = models.ImageField(upload_to=get_file_path)
    uuid = models.CharField(max_length=36, default=uuid.uuid4)


class Cart(models.Model):
    user = models.OneToOneField(User)

    def __str__(self):
        return self.user.username

    def in_cart(self, product):
        return self.cartentry_set.filter(product=product).count() > 0

    def gettotal(self):
        p = 0
        for entry in self.cartentry_set.all():
            if entry.in_stock():
                p += entry.gettotal()
        return p
    gettotal.short_description = 'total'

    def get_number_of_items(self):
        return self.cartentry_set.all().count()
    get_number_of_items.short_description = 'number of items'

    def has_physical_items(self):
        return self.cartentry_set.filter(product__physical=True).count() >= 1
    has_physical_items.boolean = True

    def clear(self):
        for entry in self.cartentry_set.all():
            entry.delete()

    def has_something_in_stock(self):
        for item in self.cartentry_set.all():
            if item.in_stock():
                return True
                break

shop/templates/shop/checkout3.html
{% extends "shop/checkoutbase.html" %}
{% block title %}Checkout Step 1{% endblock %}
{% block body %}
<div class="panel panel-default">
	<div class="panel-body">
		Please review your order. This is the final step in the checkout.
		<hr>
		<h2>Items</h2>
		{% for product in checkout.cart.cartentry_set.all %}
		{% if product.in_stock %}
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="row">
					<div class="col-md-2">
						<img src="{{ product.product.productimage_set.first.image.url }}" alt="" class="img-responsive">
					</div>
					<div class="col-md-10">
						<div class="row">
							<div class="col-md-7">
								<div class="product-name">
									<a class="cart-product-name" href="{% url 'shop:viewproduct' product.product.id %}">{{ product.product }}</a> sold by {{product.product.seller}}
								</div>
							</div>
							<div class="col-md-5">
								<div class="row">
									<div class="col-md-6">
										Price: {% if product.product.price_currency != 'OK' %}
										{{ product.product.price|floatformat }} {{ product.product.price_currency }} ({{ product.product.get_item_price|floatformat }} OK)
										{% else %}
										{{ product.product.price|floatformat }} OK
										{% endif %}
									</div>
									<div class="col-md-6">
										Quant.: <span class="quantity">{{ product.quantity }}</span>
									</div>
								</div>
								<div class="row">
									<div class="subtotal col-sm-12">Subtotal: <span class="price">{{ product.gettotal|floatformat }} OK</span></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		{% endif %}
		{% endfor %}
		<hr>
		<h2>Paid by Wallet</h2>
		<p>This order will be paid from the <strong>{{ checkout.wallet.label }}</strong> wallet, which currently has {{ checkout.wallet.get_balance|floatformat }} OK.</p>
		<hr>
		{% if checkout.shipping %}
		<h2>Shipping Address</h2>
		This order will be sent to {{ checkout.shipping.address1 }}, {{ checkout.shipping.state }}, {{ checkout.shipping.country }}.
		<hr>
		{% endif %}
		<h2>Price breakdown</h2>
		<h3>Items: {{ checkout.cart.gettotal|floatformat }} OK</h3>
		{% for item in checkout.cart.cartentry_set.all %}
		{% if item.in_stock %}
		{{ item.quantity }}&times; {{ item.product.product_name }} ({{ item.product.get_item_price|floatformat }} OK) = <span class="price">{{ item.gettotal|floatformat }} OK</span>
		{% endif %}
		{% endfor %}
		{% if checkout.shipping %}
		<h3>Shipping: {{ checkout.get_shipping_price|floatformat }} OK</h3>
		{% endif %}
		<h3>Total: {{ checkout.get_price|floatformat }} OK</h3>
	</div>
	<div class="panel-footer">
		<a href="{% url 'shop:cart' %}" class="btn btn-default">Cancel</a>
		<div class="pull-right">
			<form action="{% url 'shop:checkout' %}" method="POST">
				{% csrf_token %}
				<input type="hidden" value="{{checkout.uuid}}" name="checkout">
				<input type="hidden" value="insert interesting text here" name="confirm">
				<div class="col-sm-2"><input type="submit" class="btn btn-primary" value="Confirm checkout"></div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

shop/templates/shop/dashboard.html
{% extends "shop/base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<h1>Seller dashboard</h1>
<div class="panel panel-default">
	<div class="panel-heading">
		<div class="row">
			<div class="col-sm-2">
				EARNINGS: {% if user.usershop.get_earnings|floatformat %}{{ user.usershop.get_earnings|floatformat }}{%else%}0{% endif %} OK
			</div>
			<div class="col-sm-2">
				<a href="{% url 'shop:sales' %}">SALES: {% if user.usershop.get_purchases.count %}{{ user.usershop.get_purchases.count }}{% else %}0{% endif %}</a>
			</div>
		</div>
	</div>
	<div class="panel-body">
		<h2>My products</h2>
		<a href="{% url 'shop:sellproduct' %}" class="btn btn-block btn-primary product">Sell new item</a>
		{% for product in user.product_set.all %}
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="col-sm-2">
					<img src="{{ product.productimage_set.first.image.url }}" alt="" class="img-responsive">
				</div>
				<div class="col-sm-10">
					<a href="{% url 'shop:viewproduct' product.id %}" class="cart-product-name">{{ product.product_name }}</a><br>
					PRICE: {{ product.price|floatformat }} {{ product.price_currency }} <br>
					EARNINGS: {{ product.get_earnings|floatformat }} {{ product.price_currency }}<br>
					SALES: {{ product.get_purchases.count }}
				</div>
			</div>
			<div class="panel-footer">
				<a href="{% url 'shop:editproduct' product.id %}" class="btn btn-default">Edit</a>
				{% if not product.physical %}
				<a href="{% url 'shop:editkeys' product.id %}" class="btn btn-default">Manage keys and files</a>
				{% endif %}
			</div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}

shop/templates/shop/frontpage.html
{% extends "shop/base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
{% if not user.is_authenticated %}
<div class="jumbotron">
    <h1>Welcome to OKCart</h1>
    <div class="lead">
        The first <a href="https://okcash.co">OKCash</a> marketplace.
    </div>
    <a href="{% url 'shop:register' %}" class="btn-lg btn-primary btn">Sign up</a>
    <div><small>Alternatively, <a href="{% url 'shop:login' %}">Log in</a></small></div>
</div>
{% endif %}
{% if home_sections %}
    {% for section in home_sections %}
        <section>
            <h1>{{ section.name }}</h1>
            <div class="row">
                {% for item in section.items %}
                    <div class="col-sm-2">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <img src="{{ item.productimage_set.first.image.url}}" alt="{{ item.product_name }}" class="img-responsive">
                                <h4><a href="{% url 'shop:viewproduct' item.id %}">{{ item.product_name }}</a></h4>
                                <p>Sold by <a href="{% url 'shop:shop' item.seller %}">{{ item.seller }}</a></p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </section>
    {% endfor %}
{% endif %}
<a href="{% url 'shop:all' %}" class="btn btn-default">View all products</a>
{% endblock %}

shop/templates/shop/managekey.html
{% extends "shop/base.html" %}
{% block title %}Manage keyset{% endblock %}
{% block body %}
<h1>{% if keyset %}Edit {{ keyset.name }}{% else %}Create keyset{% endif %}</h1>
<div class="panel panel-default">
    {% load crispy_forms_tags %}
    {% crispy form %}
</div>
{% endblock %}

shop/templates/shop/product.html
{% extends "shop/base.html" %}
{% block title %}{{ product.product_name }}{% endblock %}

{% block body %}
<div class="row">
	<div class="col-md-9">
		<h1>{{ product.product_name }}</h1>
		<div class="row">
			<div class="col-md-4">
				{% if product.productimage_set.count > 0 %}
					<div class="pic-app row">
					{% verbatim %}
						<ul class="col-xs-2" style="padding: 0">
							<li v-for="(pic,index) in pics" style="display: block;">
								<a href="#" v-on:click="selected=index"><img :src="pic" class="img-thumbnail"></a>
							</li>
						</ul>
						<div class="col-xs-10">
							<img :src="pics[selected]" class="img-responsive">
						</div>
					</div>
					{% endverbatim %}
				{% endif %}
			</div>
			<div class="col-md-8">
				{{ product.product_description|linebreaks }}
			</div>
		</div>
	</div>
	<div class="col-md-3">
		<table class="table">
			<tr>
				<td>Price</td>
				<td>
					{% if product.price_currency != 'OK' %}
					{{ product.price|floatformat }} {{ product.price_currency }} ({{ product.get_item_price|floatformat }} OK)
					{% else %}
					{{ product.price|floatformat }} OK
					{% endif %}
				</td>
			</tr>
			<tr>
				<td>Rating</td>
				{% if product.review_set.all.count == 0 %}
				<td>No reviews</td>
				{% else %}
				<td>{{ product.get_rating }}/5</td>
				{% endif %}
			</tr>
			<tr>
				<td>Type</td>
				<td>{% if product.physical %}Physical{% else %}Digital{%endif%}</td>
			</tr>
			<tr>
				<td>Stock</td>
				<td>{% if product.unlimited_stock %}Unlimited{% else %}{{ product.stock }}{% endif %}</td>
			</tr>
			<tr>
				<td>Seller</td>
				<td><a href="{% url 'shop:shop' product.seller.username %}">{{product.seller}}</a></td>
			</tr>
		</table>
        {% if product.removed %}
        <a href="#" disabled class="btn btn-danger btn-disabled btn-block">PRODUCT REMOVED</a>
        {% else %}
            {% if can_buy %}
                {% if not product.in_stock %}
                    <a href="#" disabled class="btn btn-primary btn-disabled btn-block">OUT OF STOCK</a>
                {% else %}
                    {% if not incart %}
                    <a href="{% url 'shop:addtocart' product.id %}" class="btn {% if not user.is_authenticated %}btn-default{% else %}btn-primary{% endif %} btn-block">
                        {% if not user.is_authenticated %}LOGIN TO {% endif %}ADD TO CART</a>
                    {% else %}
                    <a href="#" disabled class="btn btn-primary btn-disabled btn-block">ALREADY IN CART</a>
                    {% endif %}
                {% endif %}
            {% else %}
                {% if user.is_authenticated %}
                <a href="#" disabled class="btn btn-primary btn-disabled btn-block">ALREADY OWNED</a>
                {% else %}
                <a href="{% url 'shop:login' %}?next={{ request.path }}" class="btn btn-default btn-block">LOG IN TO BUY</a>
                {% endif %}
            {% endif %}
        {% endif %}
		{% if product.seller == user %}
		<a href="{% url 'shop:editproduct' product.id %}" class="btn btn-default btn-block">Edit product</a>
		{% endif %}
	</div>
</div>
<div class="row">
	<h2>Reviews</h2>
	{% if can_review %}
	<p>
	    <button class="btn btn-default" data-toggle="modal" data-target="#review-modal">{% if reviewed %}Edit your{% else %}Write a{% endif %} review</button>
	</p>
	{% endif %}
	{% if reviews %}
	{% for review in reviews %}
	<div class="panel panel-default">
		<div class="panel-heading">
            <div class="row">
                <div class="col-sm-10">
                    <h4>{% if review.title %}{{ review.title }} - {% endif %}{{ review.rating }}/5</h4>
                </div>
            </div>
		</div>
		<div class="panel-body">
			{{ review.review|linebreaks }}
		</div>
		<div class="panel-footer">
			<div class="row">
				<div class="col-sm-4">
					Posted by {{review.user.username}} on {{review.date|date:"F jS, Y"}}
				</div>
				<div class="col-sm-4">
					<em>
						{% if review.reviewvote_set.count == 0 %}
							Nobody voted on this review
						{% else %}
							{{ review.get_percentage_100|floatformat }}% of people found this helpful (UP: {{ review.get_upvotes }} DOWN: {{ review.get_downvotes }})
						{% endif %}
					</em>
				</div>
				<div class="col-sm-4 text-right">
                    {% if review.can_delete %}
                    <a href="{% url 'shop:deletereview' product.id review.id %}" class="btn btn-default"><i class="fa fa-trash"></i></a>
                    {% endif %}
					{% if user.is_authenticated %}
						<a href="{% url 'shop:togglevote' review.id 'up' %}" class="btn {% if review.upvoted%}btn-success{%else%}btn-default{%endif%}"><i class="fa fa-thumbs-up"></i></a>
						<a href="{% url 'shop:togglevote' review.id 'down' %}" class="btn {%if review.downvoted%}btn-danger{%else%}btn-default{%endif%}"><i class="fa fa-thumbs-down"></i></a>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
	{% endfor %}
	{% else %}
	This product has no reviews
	{% endif %}
</div>
{% endblock %}
{% block modals %}
{% if can_review %}
<div class="modal fade" id="review-modal" tabindex="-1" role="dialog" aria-labelledby="review-label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="review-label">{% if reviewed %}Edit your{% else %}Write a{% endif %} review</h4>
            </div>
			{% load crispy_forms_tags %}
			{% crispy form %}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}
{% block extrascripts %}
{% load static %}
<script src="{% static 'shop/vue.js' %}"></script>
<script>
	var app = new Vue({
		el: '.pic-app',
		data: {
			pics: [
			{% for image in product.productimage_set.all %}
			"{{image.image.url}}",
			{% endfor %}
			],
			selected: 0
		}
	});
</script>
{% endblock %}

shop/templates/shop/shoppage.html
{% extends "shop/base.html" %}
{% block title %}{{ shop.user.username }}'s shop{% endblock %}
{% block body %}
<div class="row">
	<div class="col-md-3">
		<h2>{{ shop.user }}</h2>
		<p class="description">
			{{ shop.description }}
		</p>
		{% if shop.user == request.user %}
		<a href="{% url 'shop:editshop' %}" class="btn btn-default btn-block">Edit page</a>
		{% endif %}
	</div>
	<div class="col-md-9">
		{% if shop.user.product_set.count > 0 %}
		{% for product in shop.user.product_set.all %}
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="col-md-3">
					<img src="{{ product.productimage_set.first.image.url }}" alt="{{ product.product_name }}" class="img-responsive">
				</div>
				<div class="col-md-9">
					<div class="product-name">
						<a class="cart-product-name" href="{% url 'shop:viewproduct' product.id %}">{{ product }}</a> for <span class="price">{{ product.price|floatformat }}</span> {{ product.price_currency }}.
					</div>
					<div class="info">
						{% if product.unlimited_stock %}Unlimited{% else %}{{ product.stock }} in{% endif %} stock. <br>
						Product is {% if product.physical %}physical{% else %}digital{% endif %}.
					</div>
				</div>
			</div>
		</div>
		{% endfor %}
		{% else %}
		There's nothing here!
		{% endif %}
	</div>
</div>
{% endblock %}
{% if shop.can_customcss %}
{% block customhead %}
<style>
	{{ shop.custom_css }}
</style>
{% endblock %}
{% endif %}